spring.application.name=sap-kotlin-maven
spring.graphql.graphiql.enabled=true
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.profile.name=default
spring.graphql.http.path=/graphql
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis.cache=DEBUG



