app.config.check=II_AM_FROM_APPLICATION_PROPERTIES
#spring.datasource.url=jdbc:mysql://localhost:3306/pocdb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- Redis Configuration ---
# If using local Docker: localhost. If AWS: Use the ElastiCache Primary Endpoint.
# ===============================
# Redis (AWS ElastiCache)
# ===============================
#for local
#spring.data.redis.host= localhost
#For aws
spring.data.redis.host=redis-nodebased.0qfs0f.ng.0001.apse2.cache.amazonaws.com
#poccache-> name of cache
spring.data.redis.port=6379
#for local
spring.data.redis.ssl.enabled=false
#For aws
#spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=5000

# Enable Spring Cache with Redis
spring.cache.type=redis
spring.cache.redis.key-prefix=user_info::
spring.cache.redis.time-to-live=600000

#dynamodb CONFIG
aws.dynamodb.region=ap-southeast-2
aws.dynamodb.endpoint=https://dynamodb.ap-southeast-2.amazonaws.com
aws.accessKey=
aws.secretKey=